language: c
sudo: false
dist: trusty

cache:
    directories:
    - $HOME/.stack
    - .stack-work

addons:
    apt:
        packages:
        - libgmp-dev
        - libzmq3-dev

before_install:
- mkdir -p $HOME/.local/bin
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
- stack setup
- stack build --dependencies-only --fast

script:
- git repack -ad
- stack --no-terminal --skip-ghc-check test duffer
- git config --local --add repack.UseDeltaBaseOffset false
- git repack -ad
- stack --no-terminal --skip-ghc-check test duffer
- stack --no-terminal --skip-ghc-check test duffer-json duffer-streaming

after_success:
- stack install pandoc --fast
- bash .ci/update_pages.sh
